version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: rhetorical-framing-explorator-database
    environment:
      POSTGRES_DB: rhetorical-framing-explorator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rfe2023
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: rhetorical-framing-explorator-backend
    environment:
      DATABASE_URL: "postgresql://postgres:rfe2023@db:5432/rhetorical-framing-explorator"
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: rhetorical-framing-explorator-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend  

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
